### PR TITLE
Alex/top nav ui

### PR DESCRIPTION
**Pull request by FluffyPenguin**
Quick visual updates to the topNav ui.
Adds title and a fake menu button in the top right as well as text descriptions for each tab.

https://screenshot.googleplex.com/0xPoTSc3WYv

### CODE REVIEW

**Comment by r0ddy** [comment]
What is the menu icon there for?

**Comment by FluffyPenguin** [comment]
> What is the menu icon there for?

Nothing rn, just looks better with it. Can remove if we don't want it.

**Comment by r0ddy** [comment]
> > What is the menu icon there for?
> 
> Nothing rn, just looks better with it. Can remove if we don't want it.

Yeah, I was wondering if we already have the top nav, is there a need for the menu?

**Comment by FluffyPenguin** [comment]
Removed the top right menu button.

**Review by r0ddy — APPROVED** [review]
LGTM

**Pull request merged**
